// Copyright 2019 free5GC.org
//
// SPDX-License-Identifier: Apache-2.0
//

/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package producer

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/omec-project/nssf/logger"
	stats "github.com/omec-project/nssf/metrics"
	"github.com/omec-project/nssf/plugin"
	"github.com/omec-project/nssf/util"
	"github.com/omec-project/openapi/models"
	"github.com/omec-project/util/httpwrapper"
)

// Parse NSSelectionGet query parameter
func parseQueryParameter(query url.Values) (plugin.NsselectionQueryParameter, error) {
	var (
		param plugin.NsselectionQueryParameter
		err   error
	)

	if query.Get("nf-type") != "" {
		param.NfType = new(models.NfType)
		*param.NfType = models.NfType(query.Get("nf-type"))
	}

	param.NfId = query.Get("nf-id")

	if query.Get("slice-info-request-for-registration") != "" {
		logger.Nsselection.Infof("[parseQueryParameter] slice-info-request-for-registration: inn")
		param.SliceInfoRequestForRegistration = new(models.SliceInfoForRegistration)
		err = json.NewDecoder(strings.NewReader(
			query.Get("slice-info-request-for-registration"))).Decode(param.SliceInfoRequestForRegistration)
		if err != nil {
			logger.Nsselection.Infof("[parseQueryParameter] Failed to decode slice-info-request-for-registration: %v", err)
			return param, err
		}
	}

	if val := query.Get("slice-info-request-for-pdu-session"); val != "" {
		logger.Nsselection.Infof("[parseQueryParameter] Found slice-info-request-for-pdu-session")
		logger.Nsselection.Infof("[parseQueryParameter] Raw value: %s", val)
		var raw map[string]any
		if err = json.Unmarshal([]byte(val), &raw); err != nil {
			logger.Nsselection.Errorf("[parseQueryParameter] raw JSON unmarshal error: %v", err)
			return param, err
		}
		// Normalize sNssai array → object
		if snssaiRaw, ok := raw["sNssai"]; ok {
			if arr, ok := snssaiRaw.([]any); ok && len(arr) > 0 {
				logger.Nsselection.Infof("[parseQueryParameter] normalizing sNssai array → object")
				raw["sNssai"] = arr[0]
			}
		}
		var normalizedBytes []byte
		normalizedBytes, err = json.Marshal(raw)
		if err != nil {
			logger.Nsselection.Errorf("[parseQueryParameter] normalization marshal error: %v", err)
			return param, err
		}
		param.SliceInfoRequestForPduSession = new(models.SliceInfoForPduSession)
		if err = json.Unmarshal(normalizedBytes, param.SliceInfoRequestForPduSession); err != nil {
			logger.Nsselection.Errorf("[parseQueryParameter] decode error after normalization: %v", err)
			logger.Nsselection.Errorf("[parseQueryParameter] normalized JSON was: %s", string(normalizedBytes))
			return param, err
		}
		logger.Nsselection.Infof("[parseQueryParameter] Successfully decoded slice-info-request-for-pdu-session")
	}

	if query.Get("home-plmn-id") != "" {
		logger.Nsselection.Infof("[parseQueryParameter] home-plmn-id: inn")
		param.HomePlmnId = new(models.PlmnId)
		err = json.NewDecoder(strings.NewReader(query.Get("home-plmn-id"))).Decode(param.HomePlmnId)
		if err != nil {
			logger.Nsselection.Infof("[parseQueryParameter] Failed to decode home-plmn-id: %v", err)
			return param, err
		}
	}

	if query.Get("tai") != "" {
		logger.Nsselection.Infof("[parseQueryParameter] tai: inn")
		param.Tai = new(models.Tai)
		err = json.NewDecoder(strings.NewReader(query.Get("tai"))).Decode(param.Tai)
		if err != nil {
			logger.Nsselection.Infof("[parseQueryParameter] Failed to decode tai: %v", err)
			return param, err
		}
	}

	if query.Get("supported-features") != "" {
		param.SupportedFeatures = query.Get("supported-features")
	}

	return param, err
}

// Check if the NF service consumer is authorized
// TODO: Check if the NF service consumer is legal with local configuration, or possibly after querying NRF through `nf-id` e.g. Whether the V-NSSF is authorized
func checkNfServiceConsumer(nfType models.NfType) error {
	if nfType != models.NfType_AMF && nfType != models.NfType_NSSF {
		return fmt.Errorf("`nf-type`:'%s' is not authorized to retrieve the slice selection information", string(nfType))
	}

	return nil
}

// NSSelectionGet - Retrieve the Network Slice Selection Information
func HandleNSSelectionGet(request *httpwrapper.Request) *httpwrapper.Response {
	logger.Nsselection.Infof("Handle NSSelectionGet")

	query := request.Query

	response, problemDetails := NSSelectionGetProcedure(query)

	nfType := GetNfTypeFromQueryParameters(query)
	nfId := GetNfIdFromQueryParameters(query)

	if response != nil {
		logger.Nsselection.Infof("[HandleNSSelectionGet] Response: %+v", response)
		stats.IncrementNssfNsSelectionsStats(nfType, nfId, "SUCCESS")
		return httpwrapper.NewResponse(http.StatusOK, nil, response)
	} else if problemDetails != nil {
		logger.Nsselection.Infof("[HandleNSSelectionGet] Problem Details: %+v", problemDetails)
		stats.IncrementNssfNsSelectionsStats(nfType, nfId, "FAILURE")
		return httpwrapper.NewResponse(int(problemDetails.Status), nil, problemDetails)
	}
	problemDetails = &models.ProblemDetails{
		Status: http.StatusForbidden,
		Cause:  "UNSPECIFIED",
	}
	stats.IncrementNssfNsSelectionsStats(nfType, nfId, "FAILURE")
	return httpwrapper.NewResponse(http.StatusForbidden, nil, problemDetails)
}

func NSSelectionGetProcedure(query url.Values) (*models.AuthorizedNetworkSliceInfo, *models.ProblemDetails) {
	var (
		status         int
		response       *models.AuthorizedNetworkSliceInfo
		problemDetails *models.ProblemDetails
	)

	logger.Nsselection.Infof("[NSSelectionGetProcedure] Entered")

	response = &models.AuthorizedNetworkSliceInfo{}
	problemDetails = &models.ProblemDetails{}

	// Parse query parameter
	logger.Nsselection.Infof("[NSSelectionGetProcedure] Parsing query parameters: %+v", query)
	param, err := parseQueryParameter(query)
	if err != nil {
		logger.Nsselection.Infof("[NSSelectionGetProcedure] parseQueryParameter failed: %v", err)
		problemDetails = &models.ProblemDetails{
			Title:  util.MALFORMED_REQUEST,
			Status: http.StatusBadRequest,
			Detail: "[Query Parameter] " + err.Error(),
		}
		return nil, problemDetails
	}

	logger.Nsselection.Infof(
		"[NSSelectionGetProcedure] Parsed param: NfType=%v, NfId=%s, RegReqPresent=%v, PduReqPresent=%v",
		param.NfType,
		param.NfId,
		param.SliceInfoRequestForRegistration != nil,
		param.SliceInfoRequestForPduSession != nil,
	)

	// Check permission of NF service consumer
	logger.Nsselection.Infof("[NSSelectionGetProcedure] Checking NF service consumer permission")
	err = checkNfServiceConsumer(*param.NfType)
	if err != nil {
		logger.Nsselection.Infof("[NSSelectionGetProcedure] Unauthorized consumer: %v", err)
		problemDetails = &models.ProblemDetails{
			Title:  util.UNAUTHORIZED_CONSUMER,
			Status: http.StatusForbidden,
			Detail: err.Error(),
		}
		return nil, problemDetails
	}

	if param.SliceInfoRequestForRegistration != nil {
		logger.Nsselection.Infof("[NSSelectionGetProcedure] Registration flow selected")
		status = nsselectionForRegistration(param, response, problemDetails)
	} else {
		logger.Nsselection.Infof("[NSSelectionGetProcedure] PDU Session flow selected")
		status = nsselectionForPduSession(param, response, problemDetails)
	}

	logger.Nsselection.Infof(
		"[NSSelectionGetProcedure] Flow completed with status=%d, problemDetails=%+v",
		status,
		problemDetails,
	)

	if status == http.StatusOK {
		logger.Nsselection.Infof("[NSSelectionGetProcedure] Returning success response")
		return response, problemDetails
	} else {
		logger.Nsselection.Infof("[NSSelectionGetProcedure] Returning failure response with status=%d", status)
		return nil, problemDetails
	}
}

func GetNfTypeFromQueryParameters(query url.Values) (nfType string) {
	if query.Get("nf-type") != "" {
		return query.Get("nf-type")
	}
	return "UNKNOWN_NF"
}

func GetNfIdFromQueryParameters(query url.Values) (nfId string) {
	if query.Get("nf-id") != "" {
		return query.Get("nf-id")
	}
	return "UNKNOWN_NF_ID"
}
