// Copyright 2019 free5GC.org
//
// SPDX-License-Identifier: Apache-2.0
//

/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package producer

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/omec-project/nssf/logger"
	stats "github.com/omec-project/nssf/metrics"
	"github.com/omec-project/nssf/plugin"
	"github.com/omec-project/nssf/util"
	"github.com/omec-project/openapi/models"
	"github.com/omec-project/util/httpwrapper"
)

// Parse NSSelectionGet query parameter
func parseQueryParameter(query url.Values) (plugin.NsselectionQueryParameter, error) {
	var (
		param plugin.NsselectionQueryParameter
		err   error
	)
	logger.Nsselection.Infof("[parseQueryParameter]--innn")
	if query.Get("nf-type") != "" {
		param.NfType = new(models.NfType)
		*param.NfType = models.NfType(query.Get("nf-type"))
	}

	param.NfId = query.Get("nf-id")

	if query.Get("slice-info-request-for-registration") != "" {
		param.SliceInfoRequestForRegistration = new(models.SliceInfoForRegistration)
		err = json.NewDecoder(strings.NewReader(
			query.Get("slice-info-request-for-registration"))).Decode(param.SliceInfoRequestForRegistration)
		if err != nil {
			return param, err
		}
	}

	if val := query.Get("slice-info-request-for-pdu-session"); val != "" {
		logger.Nsselection.Infof("[parseQueryParameter]--Found slice-info-request-for-pdu-session in query")
		logger.Nsselection.Infof("[parseQueryParameter]--Raw JSON value: %s", val)

		// Step 1: decode into generic map
		var raw map[string]any
		if err = json.Unmarshal([]byte(val), &raw); err != nil {
			logger.Nsselection.Errorf("[parseQueryParameter] raw JSON unmarshal error: %v", err)
			return param, err
		}
		// Step 2: normalize sNssai if it's an array
		if snssaiRaw, ok := raw["sNssai"]; ok {
			if arr, ok := snssaiRaw.([]any); ok && len(arr) > 0 {
				logger.Nsselection.Infof("[parseQueryParameter] normalizing sNssai array → object")
				raw["sNssai"] = arr[0]
			}
		}
		// Step 3: re-marshal normalized JSON
		var normalizedBytes []byte
		normalizedBytes, err = json.Marshal(raw)
		if err != nil {
			logger.Nsselection.Errorf("[parseQueryParameter] normalization marshal error: %v", err)
			return param, err
		}
		// Step 4: decode into model
		param.SliceInfoRequestForPduSession = new(models.SliceInfoForPduSession)
		err = json.Unmarshal(normalizedBytes, param.SliceInfoRequestForPduSession)
		if err != nil {
			logger.Nsselection.Errorf("[parseQueryParameter] decode error for pdu-session: %v", err)
			logger.Nsselection.Errorf("[parseQueryParameter] normalized JSON was: %s", string(normalizedBytes))
			return param, err
		}

		logger.Nsselection.Infof("[parseQueryParameter]--Successfully decoded slice-info-request-for-pdu-session")
	}

	if query.Get("home-plmn-id") != "" {
		param.HomePlmnId = new(models.PlmnId)
		err = json.NewDecoder(strings.NewReader(query.Get("home-plmn-id"))).Decode(param.HomePlmnId)
		if err != nil {
			return param, err
		}
	}

	if query.Get("tai") != "" {
		param.Tai = new(models.Tai)
		err = json.NewDecoder(strings.NewReader(query.Get("tai"))).Decode(param.Tai)
		if err != nil {
			return param, err
		}
	}

	if query.Get("supported-features") != "" {
		param.SupportedFeatures = query.Get("supported-features")
	}

	return param, err
}

// Check if the NF service consumer is authorized
// TODO: Check if the NF service consumer is legal with local configuration, or possibly after querying NRF through `nf-id` e.g. Whether the V-NSSF is authorized
func checkNfServiceConsumer(nfType models.NfType) error {
	if nfType != models.NfType_AMF && nfType != models.NfType_NSSF {
		return fmt.Errorf("`nf-type`:'%s' is not authorized to retrieve the slice selection information", string(nfType))
	}

	return nil
}

// NSSelectionGet - Retrieve the Network Slice Selection Information
func HandleNSSelectionGet(request *httpwrapper.Request) *httpwrapper.Response {
	logger.Nsselection.Infof("Handle NSSelectionGet")

	query := request.Query

	response, problemDetails := NSSelectionGetProcedure(query)

	nfType := GetNfTypeFromQueryParameters(query)
	nfId := GetNfIdFromQueryParameters(query)

	logger.Nsselection.Infof("[HandleNSSelectionGet]----- response,problemdetails-status: %+v  fdgfdsg %+v", response, int(problemDetails.Status))
	if response != nil {
		stats.IncrementNssfNsSelectionsStats(nfType, nfId, "SUCCESS")
		return httpwrapper.NewResponse(http.StatusOK, nil, response)
	} else if problemDetails != nil {
		stats.IncrementNssfNsSelectionsStats(nfType, nfId, "FAILURE")
		logger.Nsselection.Infof("[HandleNSSelectionGet]----- ProblemDetailsStatus: %+v", int(problemDetails.Status))
		return httpwrapper.NewResponse(int(problemDetails.Status), nil, problemDetails)
	}
	problemDetails = &models.ProblemDetails{
		Status: http.StatusForbidden,
		Cause:  "UNSPECIFIED",
	}
	stats.IncrementNssfNsSelectionsStats(nfType, nfId, "FAILURE")
	return httpwrapper.NewResponse(http.StatusForbidden, nil, problemDetails)
}

func NSSelectionGetProcedure(query url.Values) (*models.AuthorizedNetworkSliceInfo, *models.ProblemDetails) {
	var (
		status         int
		response       *models.AuthorizedNetworkSliceInfo
		problemDetails *models.ProblemDetails
	)
	// response = &models.AuthorizedNetworkSliceInfo{}
	// problemDetails = &models.ProblemDetails{}

	// TODO: Record request times of the NF service consumer and response with ProblemDetails of 429 Too Many Requests
	//       if the consumer has sent too many requests in a configured amount of time
	// TODO: Check URI length and response with ProblemDetails of 414 URI Too Long if URI is too long

	// Parse query parameter
	param, err := parseQueryParameter(query)
	if err != nil {
		// status = http.StatusBadRequest
		problemDetails = &models.ProblemDetails{
			Title:  util.MALFORMED_REQUEST,
			Status: http.StatusBadRequest,
			Detail: "[Query Parameter] " + err.Error(),
		}
		return nil, problemDetails
	}

	// Check permission of NF service consumer
	err = checkNfServiceConsumer(*param.NfType)
	if err != nil {
		// status = http.StatusForbidden
		problemDetails = &models.ProblemDetails{
			Title:  util.UNAUTHORIZED_CONSUMER,
			Status: http.StatusForbidden,
			Detail: err.Error(),
		}
		return nil, problemDetails
	}
	response = &models.AuthorizedNetworkSliceInfo{}
	problemDetails = &models.ProblemDetails{}

	if param.SliceInfoRequestForRegistration != nil {
		logger.Nsselection.Infof("[NSSelectionGetProcedure] 111---------status: %+v", status)
		// Network slice information is requested during the Registration procedure
		status = nsselectionForRegistration(param, response, problemDetails)
	} else {
		logger.Nsselection.Infof("[NSSelectionGetProcedure] 222---------status: %+v", status)
		// Network slice information is requested during the PDU session establishment procedure
		status = nsselectionForPduSession(param, response, problemDetails)
	}
	logger.Nsselection.Infof("[NSSelectionGetProcedure]---------status: %+v", status)

	if status != http.StatusOK {
		// If validation failed (like SST check), return nil for response
		// so HandleNSSelectionGet moves to the 'else if problemDetails != nil' block
		return nil, problemDetails
	}

	return response, nil
}

func GetNfTypeFromQueryParameters(query url.Values) (nfType string) {
	if query.Get("nf-type") != "" {
		return query.Get("nf-type")
	}
	return "UNKNOWN_NF"
}

func GetNfIdFromQueryParameters(query url.Values) (nfId string) {
	if query.Get("nf-id") != "" {
		return query.Get("nf-id")
	}
	return "UNKNOWN_NF_ID"
}
